### ISSUE TITLE
marine debris data download

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#19]
One of the things we identified early on was the ability to download specific subsets of the data that a user selected through filtering... This should be considered as a high priority system improvements in the next phase of work.

**Comment by tchaddad** [comment]
The service that allows data display of filtered data should be able to provide this ability. Need clarification on download formats that would be useful to users (e.g. CSV?)

**Comment by tchaddad** [comment]
Is this as high a priority as other items in the MP list

**Comment by tchaddad** [comment]
Closing Marine Debris related issues for now
