### ISSUE TITLE
"Share this Map" preview never loads

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#23]
Preview in "Share this Map" loads logo but not map.

**Comment by tchaddad** [comment]
Definitely a bug - the map does not load in the preview pop-up, despite the URL being correct if tested in a new window. Tested in Firefox.

Not particularly a high priority item, unless the fix is a simple one. Recommend removing the Preview option until the bug can be fixed.

**Comment by fishytodd** [comment]
Appears that the actual map emden code snippet does not function either. When embedded in a website, the iframe displays the WCODP logo and a loading symbol, but does not display a map.

**Comment by tchaddad** [comment]
Preview no longer exists in the new UI, so closing this one, but embed link issue will be moved to a new ticket
