### ISSUE TITLE
Impossible to display some Cleanup org data (no item count)

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#24]
Issues with showing data that is just reported in lbs. (SOLVE)

**Comment by tchaddad** [comment]
Sounds like a bug - needs more detail so it can be followed up on - give a specific example of missing organization or data sets?

**Comment by fishytodd** [comment]
Well it was brought up by one of the Marine debris project team members referring specifically to data collected from the group SOLV in oregon. They have data in the databse but it is only reported in lbs, so there is no way to show it in the item count metrics that we are displaying within the viewer. I Think this is a larger issues related to data card standardization, and not something we will be able to easily address.

**Comment by tchaddad** [comment]
I guess the further clarification would be:
- MP is not displaying items by weight, therefore the SOLV records cannot be used (yes?)
- or is it a question of units? (sounds like no)

**Comment by fishytodd** [comment]
Correct, the planner doesn't show debris by weight as per decisions that
were made by the project team group. Recorded here so that we are still
aware this affects some organizations.

On Tue, Jan 6, 2015 at 2:28 PM, TC Haddad notifications@github.com wrote:

> I guess the further clarification would be:
> - MP is not displaying items by weight, therefore the SOLV records
>   cannot be used (yes?)
> - or is it a question of units? (sounds like no)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WCGA/Marine-Planner/issues/24#issuecomment-68946186.

## 

Todd R. Hallenbeck | Program Coordinator

West Coast Ocean Data Portal
West Coast Governors Alliance
Cell: (408) 482-6807
todd.r.hallenbeck@westcoastoceans.org
http://portal.westcoastoceans.org

**Comment by tchaddad** [comment]
OK great - I'm removing the help wanted tag and might update the title of this item so that it is a bit more clear. Also switching this from a bug to an enhancement.

**Comment by tchaddad** [comment]
Closing Marine Debris related issues for now
