### ISSUE TITLE
Data Layer Title cut off in Info Box

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#25]
Make title wrap around in Info pop up

**Comment by fishytodd** [comment]
The layer box on the left should be larger; currently each data drop-down menu cuts off after 4 layers, so scrolling through just to see all the options can be onerous. Plus longer layer names are cut off.

**Comment by tchaddad** [comment]
This is 2 issues I think (one is for info popups and one is for the main left hand navigation).

**Comment by tchaddad** [comment]
Also related:
#34 and #42

**Comment by tchaddad** [comment]
Closing because covered by other tickets
