### ISSUE TITLE
ArcServer Link Type indexing mixes up service types

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#30]
Link Type detection solution that was provided by Esri is mis-characterizing service links that come from ArcServers. Good with ArcREST, but lumps ArcServer WMS into that facet, so the individual facet numbers are off...

This was originally submitted as 2 topics in one issue, and I'm separating them into separate issues so they can be better tracked. Renaming this one to be more specific.

https://github.com/Ecotrust/wc-data-registry/issues/121

**Comment by tchaddad** [comment]
This issue is definitely still a problem and so I'm re-opening.

**Comment by tchaddad** [comment]
Ah wait, I see this is in the wrong project repo. Closing and moving over to ODP
