### ISSUE TITLE
Beach Cleanup Filter confusing

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#32]
From User Feedback Survey - I would not have known there was a drop down menu for the debris types filter had the instructions for this survey not said so. I wish there was something indicating that this were a drop down menu, I would be more likely to use it in the future.

**Comment by fishytodd** [comment]
From User Survey - Could see data when just added beach cleanup data; but when used filter by plastic bags, the data went away. This happened for any filter I tried using.

**Comment by fishytodd** [comment]
From User Survey -  However, after selecting Plastic Bags i got no results!

**Comment by fishytodd** [comment]
From User Survey - It's not immediately clear that "Plastic Bags Category" includes different types of plastic bags. Would be nice to link to a hierarchy PDF for reference and to know what is available.

**Comment by tchaddad** [comment]
Sounds like at least 2 issues here. One is a user confusion and documentation need, the second is a possible bug relating to Plastic Bag filtering. 

If there is no bug, then the first item (user confusion) is a big problem and should be high priority.

**Comment by fishytodd** [comment]
I double checked the issue and could not replicate it. Could be that there was no data for the time period specified or that the filtering tools were unclear. I believe this is addressed through better documentation or tool cues.

**Comment by tchaddad** [comment]
Closing Marine Debris related issues for now
