### ISSUE TITLE
Cleanup Bubble summaries confusing

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#33]
From User Feedback Survey -  When you click on a green circle to get more information, what do the numbers after the : mean? Number of events? Might be more consistent if displayed the number of items. Either way the user should be told what it means. Example below:

Sites
Baker Beach / 09/17/2011: 1
Bay Model Visitor Center / 09/17/2011: 1
Black Sand Beach / 09/17/2011: 1
Candlestick Point State Recreation Area / 09/17/2011: 1
Crissy Field / 09/17/2011: 1
Fort Funston / 09/17/2011: 1

**Comment by tchaddad** [comment]
Agree. If this is displaying events, then just add the word "Events" after the number. Will require a test for single vs plural.

**Comment by tchaddad** [comment]
Closing tickets related to marine debris!
