### ISSUE TITLE
Info box suggestions

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#34]
From User Feedback Survey -  Adjust the info box that pops up when user hits the info icon in the Active menu. Either make the box wider or wrap the text so the layer name isn't cut off. It'd be nice to have that box show the same information for each layer as in the catalog, rather than just name and links to data, metadata, source, wms. Finally, that box should disappear when an active layer is removed.

**Comment by tchaddad** [comment]
Falls in the category of slightly better usability

**Comment by tchaddad** [comment]
Addressed in the new UI, yay!
