### ISSUE TITLE
REST map service GetFeatureInfo capability broken

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#37]
Currently, it appears that Marine Planner no longer supports REST map service "identify" on click. Feature requested by multiple users. Worked prior to the debris layers being added.

I removed the WMS portion of this issue because that is a separate enhancement.

**Comment by emiliom** [comment]
By "REST" I assume you mean "ESRI REST"? I'm surprised to see this. I thought I remembered seeing or hearing months ago that ESRI REST "clickability" (the "identify" tool analog) was supported, and it was only WMS that wasn't. Oh well.

**Comment by tchaddad** [comment]
Unfortunately ESRI tools/training tend to use REST as a term in several different ways and users tend to conflate several different service types under this label.

To disambiguate:
- ESRI map services are dynamic (WMS equivalent) and support featureinfo queries via JSON
- ESRI cached map services are static tiles (WMTS equivalent) & do not support queries AFAIK
- ESRI feature services are dynamic (WFS equivalent) and should support featureinfo

For _DISPLAY_ in Marine Planner the first 2 service types above are supported, but not the third.

For WMS, Openlayers supports GetFeatureInfo, but this capability is not yet exposed in Marine Planner.

So back to Todd's question, I believe it is possible to expose GetFeatureInfo for WMS, but I don't believe it will be possible to expose it for ESRI cached map service (because that service type doesn't support queries).

**Comment by emiliom** [comment]
Thanks for that explanation, Tanya! I definitely didn't know about those distinctions between ESRI services, but that make a lot of sense.

**Comment by tchaddad** [comment]
Fun fact - I once tried to count how many things "ESRI REST" can mean - and from their own documentation there are about 13 distinct service types that fall under the umbrella of this term (includes different data format output options such as KML services for example). 

So when you hear someone use the term in an ESRI context, you really need to ask for specifics...

**Comment by emiliom** [comment]
Lesson learned. Thanks!

**Comment by fishytodd** [comment]
Example layer is http://coast.noaa.gov/arcgis/rest/services/MarineCadastre/PhysicalOceanographicAndMarineHabitat/MapServer/10

**Comment by fishytodd** [comment]
reached out to Anna Verrill to see if they have changed the way they publish services. In the past the critical habitat layer (above) was something that could be clicked to retrieve attribute info. No longer. But I just noticed that it is actually a feature layer that supports query function. The layer still shows up in the mp but you can't click it. Will work on finding a map service that supports identify to see if there really is a problem.

**Comment by fishytodd** [comment]
In terms of issue #37, the issue ticket has a link to a service that should support the get feature info "clickability" (also below). Im pretty sure scott confirmed this before he departed. I know that currently this layer is a sublayer. I cannot confirm if it was a sublayer when it worked. I just tried pulling it out of the table of contents and clicking on the features and they did not pop open the attribute bubble like they had in the past. Happy to do additional testing if ronan has suggestions. 

http://coast.noaa.gov/arcgis/rest/services/MarineCadastre/PhysicalOceanographicAndMarineHabitat/MapServer/10

**Comment by rcranley** [comment]
Hi @fishytodd 
Do you know when (approximately) this feature stopped working?
That'll help me in trying to diagnose what pieces were changed, that may have led to this issue.

Thanks!
- Ronan

**Comment by fishytodd** [comment]
Hey ronan, as far as I can recollect the feature stopped working around the
time we "turned on" the marine debris layers in MP. This would have been
around october of last year. These layers are being generated from data in
the marine debris database so they are treated differently that the REST or
OGC layers.

I wouldn't know what the root cause is, and our last communication with
Scott made it seem like it wasn't something obvious. But I think it had
something to do with the linking of MP with the marine debris database.

TH

On Wed, Apr 22, 2015 at 2:33 PM, rcranley notifications@github.com wrote:

> Hi @fishytodd https://github.com/fishytodd
> Do you know when (approximately) this feature stopped working?
> That'll help me in trying to diagnose what pieces were changed, that may
> have led to this issue.
> 
> Thanks!
> - Ronan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WCGA/Marine-Planner/issues/37#issuecomment-95344328.

## 

Todd R. Hallenbeck | Program Coordinator

West Coast Ocean Data Portal
West Coast Governors Alliance
Cell: (408) 482-6807
todd.r.hallenbeck@westcoastoceans.org
http://portal.westcoastoceans.org

**Comment by rcranley** [comment]
Perfect, thanks.
That gives me an idea on where to start looking.
From what I can tell, the actual click-handler hasn't changed, so my gut tells me the that there is something in the way, preventing the feature from registering that it is clicked.

I'll let you know what I find out...

**Comment by fishytodd** [comment]
Thanks, we also linked this issue with #40
https://github.com/WCGA/Marine-Planner/issues/40 (ability to do the same
with OGC WMS layers). I realize this is a different issue, because MP never
supported this, but if digging around on the REST issue provides some
opportunities for a win-win, all the better.

Thanks!

TH

On Wed, Apr 22, 2015 at 2:45 PM, rcranley notifications@github.com wrote:

> Perfect, thanks.
> That, at least give me an idea on where to start looking.
> From what I can tell, the actual click-handler hasn't changed, so my gut
> tells me the that there is something in the way, preventing the feature
> from registering that it is clicked.
> 
> I'll let you know what I find out...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WCGA/Marine-Planner/issues/37#issuecomment-95347180.

## 

Todd R. Hallenbeck | Program Coordinator

West Coast Ocean Data Portal
West Coast Governors Alliance
Cell: (408) 482-6807
todd.r.hallenbeck@westcoastoceans.org
http://portal.westcoastoceans.org

**Comment by rcranley** [comment]
I've found the issue, and will get it resolved.
I'll look into #40 and see if it will fit into the current ticket resolution window.

**Comment by tchaddad** [comment]
Looks like Ronan fixed this, so closing.
