### ISSUE TITLE
Derelict fishing gear not filterable

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#4]
Filter on Derelict gear not working properly

**Comment by tchaddad** [comment]
Progress being made on this one From Jenny 1/5/2015:

> _During some of the natural downtime over the holiday, Seth was able to dedicate a couple days to digging back in to the derelict gear issues in the Marine Debris Database that were blocking the ability to display that dataset in the data viewer._
> 
> _He made really good strides with some pretty significant rewriting of queries and tables in the Marine Debris database that the data viewer code calls.  Derelict gear is now filterable by date in the production data viewer on the filter tab.  It is, however, still not filterable by debris type.  Getting to that stage will take fairly significant additional effort as well as data clean-up in the DB because derelict gear debris types are hand-entered and vary enough by spaces, commas, etc. to block organized filtering._
> 
> _Please take a look at it and let me know if you see anything that needs our attention.  One thing we could use your help and expertise on is that, while the derelict gear in WA and CA is matching the results of the MDDB web app, we are not able to get the gear found off the coast of OR to show up. We suspect that there is a difference in the OR datasheets that creates a difference in the database that is affecting results display._

**Comment by tchaddad** [comment]
Closing Marine Debris related issues for now
