### ISSUE TITLE
OGC WMS identify/getfeatureinfo 

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#40]
Enhancement to allow MP user to click layer and get attribute info from layer. Was supported from Esri map service, but need to include OGC WMS because many providers publish this way.

**Comment by fishytodd** [comment]
@twelch What do you think about this issue? Is it something you feel comfortable with given our remaining time? Its an important one.

**Comment by twelch** [comment]
@fishytodd  Let's discuss tomorrow.  It might be possible if it's something simple that's broken.  I'm not familiar with how the MP code is deployed.  It's separate from the main Portal app.

**Comment by tchaddad** [comment]
Related to 
https://github.com/WCGA/Marine-Planner/issues/3

**Comment by tchaddad** [comment]
Fixed in the new UI - supports a wide variety of info types that might be configured on the host side.
