### ISSUE TITLE
In IE 9, info, transparency, and quite button in Activate tab are blank

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#41]
From Bridgette Lorman - noticed the problem and reported feedback. EPA and other federal agencies need to use IE. Haven't not replicated problem. 

When data layers are turned on, in activate tab, the "i" in "info" button does not appear in far left box. Same for transparency and "x" button.

**Comment by tchaddad** [comment]
Hoping that IE 9 is no longer a relevant browser, so closing this one.
