### ISSUE TITLE
Plastic bags category not showing correct active filters

### ISSUE THREAD

**Issue by fishytodd** [WCGA/Marine-Planner#43]
The plastic bags category should include "plastic bags grocery shopping trash" but it does not. The SWS snippet below shows that in the service this debris type is indeed included in the category, but this is not active on the marine planner end. 

According to the SWS (http://wcga-vm01.sdsc.edu/semantix/SWS?request=GetConceptHierarchy), both "Plastic Bags Grocery Shopping Trash" and "Plastic Bags Ziplock Snack" types are directly under the "Plastic Bags" category (see xml snippet below).

<skos:Concept rdf:about="http://marinedebris.ucc.ie/ont/140504/concept/Cat_PlasticFilms">
skos:narrower
<skos:Concept rdf:about="http://marinedebris.ucc.ie/ont/140504/concept/Cat_PlasticBags">
skos:narrower
<skos:Concept rdf:about="http://marinedebris.ucc.ie/ont/140504/concept/Plastic_bags"/>
/skos:narrower
skos:narrower
<skos:Concept rdf:about="http://marinedebris.ucc.ie/ont/140504/concept/Plastic_bags_grocery_shopping"/>
/skos:narrower
skos:narrower
<skos:Concept rdf:about="http://marinedebris.ucc.ie/ont/140504/concept/Plastic_bags_grocery_shopping_trash"/>
/skos:narrower
skos:narrower
<skos:Concept rdf:about="http://marinedebris.ucc.ie/ont/140504/concept/Plastic_bags_trash"/>
/skos:narrower
skos:narrower
<skos:Concept rdf:about="http://marinedebris.ucc.ie/ont/140504/concept/Plastic_bags_ziplock_snack"/>
/skos:narrower
/skos:Concept
/skos:narrower
…
/skos:Concept

This translates to:

Cat_PlasticFilms
  Cat_PlasticBags
    Plastic_bags
    Plastic_bags_grocery_shopping
    Plastic_bags_grocery_shopping_trash
    Plastic_bags_trash
    Plastic_bags_ziplock_snack

**Comment by fishytodd** [comment]
I also noticed that when I use the "Plastic bags grocery shopping trash" filter, it still returns all debris types from that area.

**Comment by fishytodd** [comment]
Do you know if this is only for the Plastic Bags Category or is it a symptom in all "X Category" filters?  If you aren't sure, we can check this when we dig in to it.
From what I can tell I have only seen it in the Plastic Bags category because i have been using that one much more often. Several other categories look like they are representing the individual debris types well. 

Am I correct in assuming that "Plastic Bags Grocery Shopping" + "Plastic Bags Trash" should = "Plastic Bags Grocery Shopping Trash" in terms of count?  If not, what does "Plastic Bags Grocery Shopping Trash" mean?
From what I can tell "plastic bags grocery shopping trash" is a separate debris type from both "plastic bags trash", "plastic bags grocery shopping". There is a chance that it was an introduced mistake we made in the SWS, because I don't see it as a debris type in the marine debris database. That could be why it is pulling up all the debris data when we click it because it doesn't have a "real" debris type in the database. Its possible that it should just be removed from the list. 

Do we feel confident about the counts associated with the individual 4 Plastic Bags types?  Would you like us to try to confirm that?
Its been hard to compare with marine debris database because the counts displayed there are for events not counts of debris. It would be worth verifying in a couple cases. 

Plastic Bags Category should be a full sum of all the other 4 Plastic Bags type counts?
Yes. The one caveat that I spoke with Yassine about is that we need to remove the "plastic bag ziplock bags" from this category because it isn't a type of plastic bags affected by bag bans and that is the focus of this category. It should be in plastic films I think.

**Comment by tchaddad** [comment]
Closing Marine Debris related issues for now
